// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const bookmarkPost = `-- name: BookmarkPost :exec
INSERT INTO bookmarks (user_id, post_id)
VALUES ($1, $2)
ON CONFLICT (user_id, post_id) DO NOTHING
`

type BookmarkPostParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) BookmarkPost(ctx context.Context, arg BookmarkPostParams) error {
	_, err := q.db.ExecContext(ctx, bookmarkPost, arg.UserID, arg.PostID)
	return err
}
